# Generated by Django 3.1.2 on 2020-12-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_jobseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
