# Generated by Django 3.1.2 on 2020-12-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_jobseeker_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
