# Generated by Django 3.1.2 on 2020-12-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20201225_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
