# Generated by Django 3.1.2 on 2021-01-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_auto_20210102_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
