# Generated by Django 3.1.2 on 2021-01-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_customerdetials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetials',
            old_name='Address',
            new_name='address',
        ),
    ]
