# Generated by Django 3.1.2 on 2021-01-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_verify',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
