# Generated by Django 3.1.2 on 2021-01-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_verify',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
