# Generated by Django 3.1.2 on 2021-01-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_auto_20210121_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_cancel',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
