# Generated by Django 3.1.2 on 2021-02-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='seeker_feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
