# Generated by Django 3.1.2 on 2021-02-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_feedback_seeker_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seeker_feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
