# Generated by Django 3.1.2 on 2021-02-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_auto_20210209_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='durability',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
